const data =  {
    productos:[
        {
            _id: 1,
            nombre: "Tercera equipación Temp. 21/22",
            categoria: "Camiseta",
            imagen: "/imagenes/p1.jpg",
            precio: 120,
            marca: "Adidas",
            rating: 4.5,
            numReviews: 10,
            descripcion: "descripcion",
        },
        {
            _id: 2,
            nombre: "Cuarta equipación Temp. 20/21",
            categoria: "Camiseta",
            imagen: "/imagenes/p2.jpg",
            precio: 120,
            marca: "Adidas",
            rating: 4.5,
            numReviews: 10,
            descripcion: "descripcion",
        },
        {
            _id: 3,
            nombre: "Segunda equipación Temp. 20/21",
            categoria: "Camiseta",
            imagen: "/imagenes/p3.jpg",
            precio: 120,
            marca: "Adidas",
            rating: 5,
            numReviews: 10,
            descripcion: "descripcion",
        },
        {
            _id: 4,
            nombre: "Tercera equipación Temp. 20/21",
            categoria: "Camiseta",
            imagen: "/imagenes/p4.jpg",
            precio: 120,
            marca: "Adidas",
            rating: 4.0,
            numReviews: 17,
            descripcion: "descripcion",
        },
        {
            _id: 5,
            nombre: "Primera equipación Temp. 20/21",
            categoria: "Camiseta",
            imagen: "/imagenes/p5.jpg",
            precio: 120,
            marca: "Adidas",
            rating: 4.8,
            numReviews: 26,
            descripcion: "descripcion",
        },
    ],
};

export default data;